### ISSUE TITLE
CSP error despite setting domains in Env Var list

### ISSUE THREAD

**Issue by hillsandales** [andrew-codes/playnite-web#697]
Im getting errors mentioned in #561 . Gifs and images in the description fields fail to load. I have the image source domain in OSP_ORIGINS in quotes. Doesn’t seem to work. In the container, I see that the env var is set and the values I pass in are present.

**Comment by andrew-codes** [comment]
Hi, thanks for the report. I think this is resolved in an unreleased version. I did not think it impacted most, so have not released the fix yet (it is the only thing that would be in the release). However, given it likely will resolve this issue, I'll cut a release shortly. Once the latest is released, can you please try and report back if it did or did not resolve this issue? Thanks!

**Comment by hillsandales** [comment]
I updated to v10.2.1. Wiped the database files, reloaded from Playnite. I'm still getting the CSP errors. I have the domain (and each subdomain) in the OSP_ORIGINS variable. It is loaded in the container.

For some reason, it's having a problem loading images from https://shared.akamai.steamstatic.com/. If I click the link the Chrome dev tools, the GIF opens in a new tab just fine. If I force CSP checking OFF with a Chrome plugin, the images load in the site just fine.

If there's something else to try, I will give it a shot.

**Comment by andrew-codes** [comment]
Just verifying. Are you using CSP_ORIGINS or OSP_ORIGINS? It should be csp. If this is still an issue I'll investigate further.

**Comment by andrew-codes** [comment]
I am also releasing a feature to disable csp. However if it is not working with csp then that is still an issue.

**Comment by hillsandales** [comment]
My bad! I had the variable set to CPS_ORIGINS! Changing it to CSP_ORIGINS works!
